"""Add student and vaccination models

Revision ID: 99f13afd37d4
Revises: 
Create Date: 2025-05-09 03:15:00.798852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f13afd37d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('vaccine_name')
        batch_op.drop_column('vaccination_date')

    with op.batch_alter_table('vaccination_drive', schema=None) as batch_op:
        batch_op.alter_column('drive_date',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccination_drive', schema=None) as batch_op:
        batch_op.alter_column('drive_date',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vaccination_date', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('vaccine_name', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
